#!/usr/bin/env bash
# This bash script installs nginx in your server and configures your sever block to listen to port 80 and then restarts nginx.

# Install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Configuration
mkdir /etc/nginx/html

# Configuring Nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Creating Sample Page
echo "Hello World!" > /etc/nginx/html/index.html

# Creating Server Block Files
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

}" > /etc/nginx/sites-available/default

# Start Nginx
service nginx start
