#!/usr/bin/env bash
# Configuring my Nginx server so that /redirect_me is redirecting to another page.

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

string_for_replacement="server_name _;
    rewrite ^\/redirect_me https:\/\/www.w3schools.com permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

