#!/usr/bin/env bash
# Installs Nginx with the following configurations.

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configuration
ufw allow 'Nginx HTTP'

# Creating a simple html page
echo "Hello World!" > /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.w3schools.com permanent;"sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /etc/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default

# HTTP Response Header Configuration
sudo sed -i '/^http {/a \\tadd_header X-Served-by $hostname;' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart
