#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Installs HAproxy
sudo apt-get update -y
sudo apt-get install haproxy -y

echo "
frontend GodsBook-frontend
        bind *:80
        default_backend GodsBook-backend

backend GodsBook-backend
        balance roundrobin
        server 145153-web-01 100.26.9.127 check
	server 145153-web-02 52.3.244.232 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart haproxy
sudo service haproxy restart
